### ISSUE TITLE
Gantt tiny width

### ISSUE THREAD

**Issue by fcsbr** [renanlecaro/mermaid-gdocs#10]
Gantt chart is showing only in too small width.

**Comment by renanlecaro** [comment]
@coelhofrederico which browser are you using, and can you make a screen-grab of what happened please ? 
Please find here my failed attempt to reproduce the issue : https://www.youtube.com/watch?v=mcLRQTor4dY

**Comment by fcsbr** [comment]
Hello @renanlecaro I was using Chrome.
I've just tested and now it is working fine.
Tks for the message and congrats for the add-on.
