### ISSUE TITLE
Chart not editable after changing its positionning

### ISSUE THREAD

**Issue by renanlecaro** [renanlecaro/mermaid-gdocs#13]
That's because the picture becomes a different class of document element.

**Comment by kghrfp** [comment]
I"m having the same problem.  How do you change the class of document element so that Mermaid editor can recognize it?

**Comment by renanlecaro** [comment]
Switching the image positioning back to its original mode should work as a temporary workaround, the source of the graph is stored in the meta description of the picture, that shouldn't have been removed by Google docs when switching the positioning mode of the picture. Handling different alignments is not completely trivial, so it won't be fixed soon. But I understand that's a bummer

**Comment by kghrfp** [comment]
Thanks for the quick reply.  I did figure that out and was able to continue
editing.

**Comment by Nittarab** [comment]
If you move the image using cut and paste you will be able to edit the chart :wink:

**Comment by renanlecaro** [comment]
When you make a image "float" it goes from being a [InlineImage](https://developers.google.com/apps-script/reference/document/inline-image ) to a [PositionedImage](https://developers.google.com/apps-script/reference/document/positioned-image).

Those cannot really be detected by the plugin, you'd need to select the paragraph that they are anchored to. I also can't read/write the meta title/description on those pictures. As long as those problems persist, editing of PositionedImage in this plugin won't be possible

**Comment by renanlecaro** [comment]
There's now a hint in case the user tries to edit an empty selection 
![image](https://github.com/renanlecaro/mermaid-gdocs/assets/3457214/7199b175-7118-47d6-8c59-4c74a7405762)
