### ISSUE TITLE
Google slide compatibility

### ISSUE THREAD

**Issue by renanlecaro** [renanlecaro/mermaid-gdocs#15]
No reason not to have it

**Comment by ChristopherLenz** [comment]
> No reason not to have it

Agree! But why do you changed your mind?

**Comment by renanlecaro** [comment]
Well my reason is that I just have other projects to work on. No point in keeping issues open for every feature that would be nice but i won't have the time to work on. I assume i'd need to learn about how slide handles its picture elements, which is surely different from docs

**Comment by renanlecaro** [comment]
PR welcome though
