### ISSUE TITLE
Autocompletion for Node names

### ISSUE THREAD

**Issue by johannchopin** [renanlecaro/mermaid-gdocs#18]
First thanks for your work @renanlecaro 👏 This extension is really helpful.

It could be a cool idea to add autocompletion on top of the cursor for the mermaid nodes:

```
%% Here the nodes are Page and Section
graph TB
    Page["⚛️Page"]
    Section["⚛️Section"]
```

So when you start writing `Sec...` it will propose you `Section`. Then as a user I don't need to rewrite it or copy-paste it 👍

**Comment by renanlecaro** [comment]
Thanks for the suggestion. I think this would require a considerable effort, and I have some other projects that are higher priority, so I won't develop this myself. However I'd be happy to merge a pr on this topic. The source code for the client side is very short, so it's not a really hard project to contribute to.

**Comment by johannchopin** [comment]
@renanlecaro Yep sure I add in mind to add that by my own. Will try to implement it by the end of next week 👍
