### ISSUE TITLE
Behavior deviation from live editor

### ISSUE THREAD

**Issue by lgilson** [renanlecaro/mermaid-gdocs#20]
Hi,

the chars < and > are somehow special within the google docs environment. The example diagram below will wok fine in the live editor at https://mermaid-js.github.io/mermaid-live-editor/edit , but will add another ```</john>``` at the end in google docs. 

Depending on the content of the < ... > sequence, the diagram fails to render at all.

```
sequenceDiagram
    Alice->>+John: Hello <John>, how are you?
```

Thanks,
Laurent

**Comment by renanlecaro** [comment]
![image](https://user-images.githubusercontent.com/3457214/132107360-f4394afd-e1aa-455b-b007-7361d03b2d13.png)
Thank you for the report with clear steps to reproduce. I was using innerHTML where I should have been using textContent. Should be fixed by now
