### ISSUE TITLE
Not working on Chrome on Mac

### ISSUE THREAD

**Issue by 8itbangr** [renanlecaro/mermaid-gdocs#21]
I installed from Google Marketplace.  Mermaid appears under the Add-ons, and I am able to choose chart types to insert.  When I fill anything in to make a chart, I get nothing on the right side of the dialog, even when I'm sure it's good mermaid code.
I also checked in Incognito, in case another extension was interfering, but it acts the same there.  Also tried in a brand new document.
Chrome is 95.0.4638.69

**Comment by brittm42** [comment]
I'm having this same issue

**Comment by 23tux** [comment]
+1 I also have the same issue. However, it works on FF on my Mac

**Comment by renanlecaro** [comment]
Oh my i'm only seeing this now, i shoudln't have muted github in my inbox. I just tried to test it, but google won't let me log in with the chrome mac os instance provided by browserstack. Can you send me a report of the console output (screenshot or copy paste) please. That could help me a bit

**Comment by renanlecaro** [comment]
@8itbangr @britt-uma @23tux can you compare the behavior of chrome and firefox when clicking "insert" on this page https://coruscating-eclair-bc8b43.netlify.app/ ?


 I tried to reproduce the issue in Browserstack without success. Browserstack lets me "remote control" all sorts of machines to test websites on them. However, Browserstack's IP seems to be blocked by google, and so I can't test the complete version of the addon running in prod. I can still however test my code as a separate website (the netlify thing) and I don't see any problem on catalina and chrome 95, or monterey and chrome 103

**Comment by gautierchomel** [comment]
> I installed from Google Marketplace. Mermaid appears under the Add-ons, and I am able to choose chart types to insert. When I fill anything in to make a chart, I get nothing on the right side of the dialog, even when I'm sure it's good mermaid code.

Same problem with Chromium Version 105.0.5195.102 (Official Build) on Debian 11.3 (64-bit)

**Comment by renanlecaro** [comment]
Just deployed a new version of the app, is it still happening ?
Confirmed working on Chrome 112.0.5615.49 and mac os 12.6
Confirmed working in firefox 102.0 on ubunutu Ubuntu 21.10
Confirmed working in chrome 111.0.5563.64 on ubunutu Ubuntu 21.10
