### ISSUE TITLE
Requested permissions excessive?

### ISSUE THREAD

**Issue by geksiong** [renanlecaro/mermaid-gdocs#22]
Can we have a reduced scope of permissions?

Currently, this is what's requested:

- See, edit, create, and delete all your Google Docs documents

I also have the PlantUML Gizmo add-on, and it requests for a smaller scope:

- View and manage documents that this application has been installed in

I think that's a better scope to request for, and it gives us better peace of mind. The current permission is preventing me from using the add-on for work.

**Comment by quasipickle** [comment]
I'll chime in that I too want to use this for work, but can't justify giving this access to _all_ my documents.

**Comment by jonz-secops** [comment]
Agreed, let's see a minimal set of permissions requested. As is, the access scope is way beyond what is appropriate for a professional environment.

**Comment by renanlecaro** [comment]
Agreed that it would be better.  I have other things to focus on right now. If one of you would like to integrate the app better with google docs (ask less permissions, use in slides..), I'd be happy to pass this project on

**Comment by samadhicsec** [comment]
I also would like to use this add-on, but the permissions make it a challenge to use in a business context.

According to this page https://developers.google.com/apps-script/add-ons/concepts/editor-scopes#editor_add-on_scopes, to fix this all you need to do is add:

`/**`
`   * @OnlyCurrentDoc`
`   */`

To the top of the Code.gs file.

I wasn't able to get the add-on working myself, but I got it working enough (with the above change) to prove that the change causes it to ask for reduced permissions, but I couldn't confirm that all the functionality still worked.

**Comment by renanlecaro** [comment]
I made an update to the scope, pending verification by google

**Comment by renanlecaro** [comment]
![image](https://user-images.githubusercontent.com/3457214/182255760-fa3f02ab-30eb-4ba1-988a-c422159493be.png)
Google's scopes review policy is just the worst

**Comment by renanlecaro** [comment]
Well, it was a pain, but i think it's good now @geksiong @quasipickle @jonz-secops @samadhicsec 

![image](https://user-images.githubusercontent.com/3457214/183239036-25d75bd0-77e5-4912-a4aa-4ed57e2229c8.png)

**Comment by renanlecaro** [comment]
I couldn't get rid of the email adress and public info part, i guess all addons get it by default ?

**Comment by samadhicsec** [comment]
Your pain will improve the efficiency of a whole lot of people.  My sincere thanks for making the update.
