### ISSUE TITLE
Font Awesome Support

### ISSUE THREAD

**Issue by agizis** [renanlecaro/mermaid-gdocs#25]
I see the old ticket which you closed but when i put fontawesome in a diagram it shows in the preview, but not once i put it in the real doc.

![image](https://user-images.githubusercontent.com/7276708/194782583-faa912cb-0096-4b87-a124-89fc2dffd738.png)

![image](https://user-images.githubusercontent.com/7276708/194782613-a5230736-601a-4f82-96b0-e3372afd25de.png)

**Comment by agizis** [comment]
Tried in both Chrome and Firefox on Windows, same in both, if that matters.

**Comment by renanlecaro** [comment]
Hi, i gave it another go, generating the png from the svg with icons is not trivial. My short attempt didn't work, and i'd need to use an extrernal serice like https://mermaid.ink to do it, which brings another set of problems

**Comment by renanlecaro** [comment]
Now the icons don't show in the preview, i guess that's better. i'm not planning to add this feature, because it seems to require generating graphs server side, which has data security implications.
