### ISSUE TITLE
FR: Support Slides

### ISSUE THREAD

**Issue by Lockszmith-GH** [renanlecaro/mermaid-gdocs#26]
Currently, only working in Docs.
Would it be possible to add support so the Add-On works in Slides as well?

Great add-on BTW.

**Comment by meizy** [comment]
+1 !

**Comment by karstenthygesen** [comment]
Also +1 from me - it would be very useful in Google Slides as well...

**Comment by mjpieters** [comment]
Work-around: You can copy a rendered Mermaid diagram from Google Docs to Google Slides.

Given that there is no good SVG-to-Slides import path any more, this is a workable poor-man's alternative.

**Comment by renanlecaro** [comment]
@Lockszmith-GH @meizy @karstenthygesen @mjpieters i've added Slides Support now, let me know if there are any issues.

**Comment by Lockszmith-GH** [comment]
@renanlecaro - this is awesome. It works great.

Thank you for this.
