### ISSUE TITLE
update to latest mermaid version

### ISSUE THREAD

**Issue by meizy** [renanlecaro/mermaid-gdocs#27]
great add-on!

could you update to latest mermaid version?

thanks

**Comment by renanlecaro** [comment]
I hotlink to https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js which is supposed to contain the latest version. it's not a great practice but it's the easiet way to avoid having a ticket like this every month. Can you provide evidence that the version isn't up to date please ?

**Comment by meizy** [comment]
I tried to use a timeline diagram, which was introduced in 9.4, and it didn't work. Wrong conclusion on my side?

**Comment by renanlecaro** [comment]
An update should now be released with mermaid v10
