### ISSUE TITLE
RFE: adding support for C4 Diagrams

### ISSUE THREAD

**Issue by dabelenda** [renanlecaro/mermaid-gdocs#28]
In our organization we standardized on writing C4 diagrams for context.
We were searching a way to add diagrams to gdocs and found this application that seem very promising since mermaid can handle C4 diagrams (beta feature, but still better than nothing) see: https://mermaid.js.org/syntax/c4c.html

It would be great to add support for C4 diagrams, from what I understand it should be a tiny modification to this test https://github.com/renanlecaro/mermaid-gdocs/blob/master/src/index.js#L119

**Comment by dabelenda** [comment]
it seems I was wrong in my assumption

**Comment by dabelenda** [comment]
It seems I was right in my assumption that modification of the application was necessary to add new diagrams, but pointed to the wrong file: https://github.com/renanlecaro/mermaid-gdocs/blob/master/google%20scripts/Code.gs#L10-L21

**Comment by dabelenda** [comment]
Oh, you can ignore the snippet and add your C4 Diagram directly without caring about which type of diagram you added from the menu.

**Comment by renanlecaro** [comment]
An update should now be released with mermaid v10. I removed the graph suggestions from the menu and just linked to the help
