### ISSUE TITLE
Extension stopped working after updating Chrome

### ISSUE THREAD

**Issue by parasaurolophus** [renanlecaro/mermaid-gdocs#29]
The plugin was working well but now has stopped functioning. The only thing I know of that changed was upgrading to the latest version of Chrome.

The symptom is that the extension UI loads but is non-functional. A series of error messages are logged to the browser console each time the extension UI is launched. (See attached)

Chrome version: Version 111.0.5563.146 (Official Build) (arm64)
OS: macOS Ventura 13.3

[mermaid-plugin-errors.log](https://github.com/renanlecaro/mermaid-gdocs/files/11115609/mermaid-plugin-errors.log)

**Comment by renanlecaro** [comment]
Just deployed a new version of the app, is it still happening  ? 
Confirmed working on Chrome 112.0.5615.49 and mac os 12.6
