### ISSUE TITLE
Can't insert graph

### ISSUE THREAD

**Issue by nrmmota** [renanlecaro/mermaid-gdocs#35]
Hi,
Every time I try to insert a graph a message popups stating I don't have permission to do the action.
![image](https://github.com/renanlecaro/mermaid-gdocs/assets/4120514/b461303c-6b57-4d8a-9521-ee94bb3dad94)

Regards,
Nuno

**Comment by amitgol-wand** [comment]
This is a common issue with other add-ons as well, and the solution is to first sign out of all your accounts and then sign into the one you installed the add-on
