### ISSUE TITLE
This document requires 'TrustedHTML' assignment

### ISSUE THREAD

**Issue by tirsen** [renanlecaro/mermaid-gdocs#36]
Thank you so much for a super awesome plugin. I use it almost every day!

I'm so sad that it has stopped working. I get the following error:
This document requires 'TrustedHTML' assignment.
I0 @ mermaid-d06ecb0d.js:5603

I hope you can fix it. Thanks again!

**Comment by renanlecaro** [comment]
Seems to be a problem with chrome, works fine in firefox for me. I'll investigate

**Comment by renanlecaro** [comment]
Seems to be related to chrome settings for "third-party cookies" being set to "block third-party cookies". It makes the loading of the user's favorite theme crash.

**Comment by renanlecaro** [comment]
I pushed an update that removed the "save favorite theme" behavior as it didn't really seem to work anyway

**Comment by renanlecaro** [comment]
@tirsen is the issue resolved ?
