### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by rawdlite** [renanlecaro/mermaid-gdocs#37]
Hi,

i like your plugin very much, as it helps collaboration on a chart.
Unfortunately it does not work in in my Chrome Browser (Version 119.0.6045.199 on OSX)
Works fine in Safari.
On Chrome it does not render the graph. In the graph area the source code is shown.
Let me know whether and what further information you need to track this down.

TIA tom

**Comment by rawdlite** [comment]
Uuups, read the limitations after writing the issue.

`seems to bug with google chrome on mac`

can attest it does not work with chrome on mac.
Anything i can do to support you with this issue?

cheers tom

**Comment by rawdlite** [comment]
Got this in the console. HTH

<ol class="tree-outline hide-selection-when-blurred issues" role="tree" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; padding: 0px; margin: 0px; z-index: 0; position: relative; overflow: auto; --issue-indent: 8px; list-style-type: none; color: rgb(189, 198, 207); font-family: &quot;.SFNSDisplay-Regular&quot;, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(40, 40, 40); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li role="treeitem" class="issue parent expanded" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; padding-top: 0px; padding-right: 8px; padding-bottom: 0px; padding-left: var(--issue-indent); overflow: hidden; flex: 0 0 auto; transition: background-color 200ms ease 0s; border-top-color: ; border-top-style: ; border-right-color: ; border-right-style: ; border-bottom-color: ; border-bottom-style: ; border-left-color: ; border-left-style: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-width: 0px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: var(--sys-color-state-hover-on-subtle);"><div class="header" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row; align-items: flex-start; padding: 4px 0px; cursor: pointer; width: 676.234px;"><div class="title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 0%; font-size: 14px; color: var(--sys-color-on-surface); font-weight: 450; user-select: text; padding-top: 2px;">Trusted Type expected, but String received</div><devtools-hide-issues-menu class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; visibility: visible;"><button class="hide-issues-menu-btn" title="Hide issues" style="position: relative; display: flex; background-color: transparent; flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; margin: 0px -2px 0px 4px; overflow: hidden; border-radius: 0px; border: none; --icon-color: var(--icon-default);"><devtools-icon style="display: inline-block; white-space: nowrap; position: relative;"><div class="icon-basic" style="width: 20px; height: 20px; display: block; -webkit-mask-image: url(&quot;devtools://devtools/bundled/devtools-frontend/front_end/Images/dots-vertical.svg&quot;); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: 99%; background-color: var(--icon-color, var(--icon-color));"></div></devtools-icon></button></devtools-hide-issues-menu></div></li><ol class="children body issue-kind-page-error expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding-left: calc(var(--issue-indent) + 43px); border-bottom: 1px solid var(--sys-color-divider); padding-top: 6px; position: relative; padding-bottom: 26px; padding-right: 8px; display: block;"><li role="treeitem" class="always-parent" aria-posinset="1" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><devtools-markdown-view style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="message" style="line-height: 20px; font-size: 14px; color: var(--color-text-secondary); margin-bottom: 4px; user-select: text;"><p style="margin-bottom: 16px; margin-block-start: 2px;">Your site tries to use a plain string in a DOM modification where a Trusted Type is expected. Requiring Trusted Types for DOM modifications helps to prevent cross-site scripting attacks.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">To solve this, provide a Trusted Type to all the DOM modifications listed below. You can convert a string into a Trusted Type by:</p><ul style="list-style-type: none; list-style-position: inside; padding-inline-start: 0px;"><li style="margin-top: 8px; display: list-item;">defining a policy and using its corresponding<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">createHTML</code>,<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">createScript</code><span> </span>or<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">createScriptURL</code><span> </span>function.</li><li style="margin-top: 8px; display: list-item;">defining a policy named<span> </span><code style="color: var(--color-text-primary); font-size: 12px; user-select: text; cursor: text; background: var(--color-background-elevation-1);">default</code><span> </span>which will be automatically called.</li></ul></div></devtools-markdown-view></li><li role="treeitem" class="always-parent parent expanded affected-resources-label" aria-expanded="true" aria-posinset="2" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; margin-top: 5px; font-size: 10px; font-weight: 500; letter-spacing: 0.06em; text-transform: uppercase; color: var(--sys-color-on-surface); display: flex; text-overflow: ellipsis; white-space: normal; position: relative; align-items: flex-start;">AFFECTED RESOURCES</li><ol class="children expanded affected-resources" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 3px 0px 0px; position: relative; user-select: text; display: block;"><li role="treeitem" class="parent expanded" aria-expanded="true" aria-posinset="1" aria-setsize="1" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start; margin-top: 0px; padding: 2px 5px 0px; background: var(--sys-color-cdt-base-container);"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><div class="affected-resource-label" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-size: 14px; line-height: 20px; color: var(--sys-color-on-surface); position: relative; cursor: pointer;">2 directives</div></li><ol class="children expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 6px 0px 9px 5px; display: block; background: var(--sys-color-cdt-base-container); margin-bottom: 10px;"><li role="treeitem" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span>
Source Location | Status
-- | --
mermaid-d06ecb0d.js:5603 | blocked
userCodeAppPanel:82 | blocked

</li></ol></ol><li role="treeitem" class="always-parent link-wrapper selected" aria-posinset="3" aria-setsize="3" tabindex="0" aria-selected="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; outline-width: 0px; margin-top: 15px; user-select: text; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><ul class="link-list" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; list-style-position: inside; padding-inline-start: 0px;"><li style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><x-link class="link devtools-link" tabindex="0" role="link" target="_blank" rel="noopener" href="https://web.dev/trusted-types/#fix-the-violations" title="https://web.dev/trusted-types/#fix-the-violations" style="box-sizing: border-box; min-width: 0px; min-height: 0px; cursor: pointer; text-decoration: underline; color: var(--sys-color-primary); outline-offset: 2px; font-size: 14px; padding-top: 4px; display: inline;"><devtools-icon class="link-icon" style="display: inline-block; white-space: nowrap; position: relative; box-sizing: border-box; min-width: 0px; min-height: 0px; vertical-align: sub; margin-right: 0.5ch;"><div class="icon-basic" style="width: 16px; height: 16px; display: block; -webkit-mask-image: url(&quot;devtools://devtools/bundled/devtools-frontend/front_end/Images/open-externally.svg&quot;); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: 99%; background-color: var(--icon-color, var(--icon-link));"></div></devtools-icon>Learn more: Trusted Types - Fix violations</x-link></li></ul></li></ol></ol>

**Comment by renanlecaro** [comment]
thanks for the detailed reporting. sadly i can't really work on this without a mac. i'll try to borrow one from a friend

**Comment by ardigan6** [comment]
@renanlecaro also look forward to a fix!

you can use one of the free services like https://www.browserstack.com/open-source to easily test this. [docs](https://www.browserstack.com/question/61683)

**Comment by renanlecaro** [comment]
Google rejected my login attempts when using browserstack, so I couldn't really see the problem, if I remember well

**Comment by renanlecaro** [comment]
I juste tried it on chrome on an M2 mac and didn't have any issue. It might be because it's an ARM macbook, it might be the chrome version, or it might be that the bug is gone. Do you still experience the issue those days @ardigan6  ?

**Comment by renanlecaro** [comment]
No updates on this, i'll assume it was some temp problem that got fixed with an update of chrome
