### ISSUE TITLE
Add support for customising configuration

### ISSUE THREAD

**Issue by matdehaast** [renanlecaro/mermaid-gdocs#4]
Thanks for this great tool!

Would be great to add support for customising the configuration object

**Comment by renanlecaro** [comment]
@matdehaast this would be quite easy to do as we just need to add another key to the json we store in alt text. However, i'm not sure of how to get this to look good ui wise, a json blob editor is not really user friendly. Feel free to submit a pr.

**Comment by renanlecaro** [comment]
@matdehaast except the theme, is there anything that should be configurable ? I'd like to close this issue unless there's something worth doing here
