### ISSUE TITLE
Center the diagram

### ISSUE THREAD

**Issue by Piratepie** [renanlecaro/mermaid-gdocs#40]
Centering the diagram to the middle just looks nicer imo :)

Currently:
![image](https://github.com/renanlecaro/mermaid-gdocs/assets/27888345/1c5633e6-f11c-4961-a096-502a94f5a792)

Suggested:
![image](https://github.com/renanlecaro/mermaid-gdocs/assets/27888345/80c0374e-e90c-46a8-a80f-61d0e9b52c2a)

**Comment by renanlecaro** [comment]
I applied the suggested styles.
