### ISSUE TITLE
Can the auto-resize be stopped when the diagram is edited?

### ISSUE THREAD

**Issue by bjohas** [renanlecaro/mermaid-gdocs#42]
Hello,

Great plugin!

When I update a diagram, the diagram 'forgets' its size (of the inserted image). Is it possible to edit a diagram while maintaining the size. I.e.,

- edit diagram
- reize the resulting picture
-  edit diagram + save
- picture is back to previous size.

Can that be changed?

**Comment by renanlecaro** [comment]
Should be the case now.  When you open an image to edit it, I'm sending its size to the popup along with the mermaid source code. I then compare the preview of your code to how big the image was in the doc. And when you save, I apply the same scaling back to the newly created image. 

https://github.com/user-attachments/assets/2d8db7c5-b48b-4994-a9a6-eacdd85f1b52
