### ISSUE TITLE
Error when inserting to google docs

### ISSUE THREAD

**Issue by mc-lijauco** [renanlecaro/mermaid-gdocs#47]
<img width="326" alt="image" src="https://github.com/user-attachments/assets/ccf0be4a-4784-40c2-94a7-0307b45c21d5">

**Comment by renanlecaro** [comment]
This is a known issue, the "authorization is required" message usually means that you are logged in to multiple google accounts, and the plugin will only work for the first one you logged in. This is a google docs bug. As explained in the message, the simplest solution is to log out of all google accounts, then log back in to the one you want to use with gdocs plugins.
