### ISSUE TITLE
Cannot recognize Expanded Node Shapes in Mermaid Flowcharts (v11.3.0+)

### ISSUE THREAD

**Issue by mc-lijauco** [renanlecaro/mermaid-gdocs#48]
<img width="263" alt="image" src="https://github.com/user-attachments/assets/6ec2c892-a009-4872-817f-8c11baf8ba36">

https://mermaid.js.org/syntax/flowchart.html#expanded-node-shapes-in-mermaid-flowcharts-v11-3-0

**Comment by renanlecaro** [comment]
Right, it's hardcoded to load v10, so that makes sense. I'll update to v11

**Comment by renanlecaro** [comment]
Updated, should work now in slides and docs
![image](https://github.com/user-attachments/assets/f968e635-c087-4c7d-b43d-f9f9d761606c)
![image](https://github.com/user-attachments/assets/2baae9b9-e130-4e27-bead-ef110487232b)
