### ISSUE TITLE
Gantt Diagram cannot be edited

### ISSUE THREAD

**Issue by fbertoia** [renanlecaro/mermaid-gdocs#7]
Hello,

Mermaid on GDocs works perfectly, except for the Gantt Diagram.
When you insert it the first time, it works fine, but when you try to edit the Gantt Diagram, it says ```Please selecte an existing chart created with this app first.``` whereas for others, it can be edited.

Have you had that issue ?
Thank you

**Comment by renanlecaro** [comment]
Seems like it works after the update, now sure what happened before https://youtu.be/iavlFULrpos
