### ISSUE TITLE
Can't scroll to "submit" button

### ISSUE THREAD

**Issue by carlosbarilatti** [renanlecaro/mermaid-gdocs#9]
If the diagram is fairly not that small, the insert button is hidden below the SVG. Probably some `z-index` and `overflow: scroll` styling would fix the issue. Let me know if you need any help!

Update: Expanding the `textarea` helps in showing the button.

**Comment by renanlecaro** [comment]
Thank you for reporting this issue, should be fixed now
![image](https://user-images.githubusercontent.com/3457214/74430285-e38f5280-4e5c-11ea-8d75-484d45127d85.png)

**Comment by renanlecaro** [comment]
Oh, i just realized that the fix doesn't work in Chrome, only in firefox

**Comment by renanlecaro** [comment]
This should be fixed in chrome and Firefox now.
